version: '3.8'

services:

  web:
    build: .
    command: bash -c "PYTHONPATH=$(pwd) python ./src/main.py"
    ports:
      - 8004:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    hostname: postgres
    image: postgres:15.3
    expose:
      - 5432
    env_file:
      - .env