"""09.12.2024 10:32

Revision ID: 26e95a7e2435
Revises: f9b8dc273c0e
Create Date: 2024-12-09 10:32:27.735752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e95a7e2435'
down_revision: Union[str, None] = 'f9b8dc273c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_bot')
    # ### end Alembic commands ###
