"""18.10.2024 19:04

Revision ID: 2ea8aaa49e63
Revises: 5fa09f798344
Create Date: 2024-10-18 19:04:22.158456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea8aaa49e63'
down_revision: Union[str, None] = '5fa09f798344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'chat_id')
    # ### end Alembic commands ###
