"""18.10.2024 19:18

Revision ID: 67f1a7ca9937
Revises: 2ea8aaa49e63
Create Date: 2024-10-18 19:18:08.863927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f1a7ca9937'
down_revision: Union[str, None] = '2ea8aaa49e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_recipient_id_fkey', 'message', type_='foreignkey')
    op.drop_column('message', 'recipient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('message_recipient_id_fkey', 'message', 'user', ['recipient_id'], ['user_id'])
    # ### end Alembic commands ###
