"""09.12.2024 10:34

Revision ID: 910a63171c93
Revises: 26e95a7e2435
Create Date: 2024-12-09 10:34:09.345214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910a63171c93'
down_revision: Union[str, None] = '26e95a7e2435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_bot',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_bot',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
