"""22.11.2024 13:27

Revision ID: b033b5b9f052
Revises: 04d93e9cf7ee
Create Date: 2024-11-22 13:27:30.457987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b033b5b9f052'
down_revision: Union[str, None] = '04d93e9cf7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_bot',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_bot',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
