"""06.10.2024 16:00

Revision ID: f563f7d22261
Revises: 486d28769dfe
Create Date: 2024-10-06 16:00:28.841839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f563f7d22261'
down_revision: Union[str, None] = '486d28769dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'user_agent')
    # ### end Alembic commands ###
